services:
  rttys:
    image: "rttys:latest"
    restart: "unless-stopped"
    ports:
      - "5912:5912"
      - "5913:5913"
      - "5914:5914"
    volumes:
      - /opt/rttys:/etc/rttys
    command: run --addr-http-proxy :5914